name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache SBT dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', 'project/**') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
          
    - name: Run tests and build
      run: sbt clean test package assembly
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scala-jars
        path: target/scala-2.12/*.jar